### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [pyramation/postgres-ast-deparser#1]
Say I wanted to port this to a [pgx](https://github.com/tcdi/pgx) extension... how is the code currently licensed?  I may have overlooked it, but I don't see one.

**Comment by pyramation** [comment]
ooops, let me add one ! will be MIT

**Comment by pyramation** [comment]
https://github.com/pyramation/postgres-ast-deparser/blob/master/packages/ast/LICENSE

**Comment by pyramation** [comment]
@eeeebbbbrrrr if possible, can you name it, `ast`? not sure if there are limitations — happy however you can make it happen. Thanks!

Here is the extension packaged up if you need it https://github.com/pyramation/postgres-ast-deparser/blob/master/packages/ast/sql/ast--13.0.1.sql
