### ISSUE TITLE
Use of native gen_random_uuid() since PG 13

### ISSUE THREAD

**Issue by fljdin** [pyramation/postgres-ast-deparser#2]
Hi!

As documented, the `uuid-ossp` extension is required and (as far I looked up) there are a few test files using dedicated `uuid_generate_v4()` method.

Since PostgreSQL v13, a native method has been added `gen_random_uuid()` and could be used in place to reduce dependancies.
What do you think about?

Regards, Florent

**Comment by pyramation** [comment]
thanks @fljdin !!

Actually, realizing the tests were just ast deparsing, the lib wasn't even necessary! thanks! it's been removed https://github.com/pyramation/postgres-ast-deparser/commit/d652b311074aaa9271fd9e0c4d0951e207c6369d

Let me know if I missed anything, cheers!
