### ISSUE TITLE
Handle multiple statements in a transaction

### ISSUE THREAD

**Issue by fljdin** [pyramation/postgres-ast-deparser#7]
Hi!

What do you think about making a `ast.raw_stmts()` or `ast.raw_transaction` method?

Similar to method `ast.raw_stmt()`, this one could handle an array of statements in the same jsonb tree, in case of multiple statements are linked together. A more advanced use-case can be a complete transaction body with `BEGIN`, ordered statements and a final `COMMIT`, isolation level could also be passed as argument.

Expected result:

```sql
SELECT deparse.expression(ast.raw_transaction(
  v_stmts := jsonb(ARRAY[
    ast.create_stmt(
        v_relation := ast.range_var(v_schemaname := 'public', v_relname := 'my_table_1')),
    ast.create_stmt(
        v_relation := ast.range_var(v_schemaname := 'public', v_relname := 'my_table_2')),
  ]),
  v_isolation_level := 'REPEATABLE READ'
));
```
```
BEGIN;
SET transaction_isolation = "repeatable read";
CREATE TABLE public.my_table1();
CREATE TABLE public.my_table_2();
COMMIT;
```
Regards, Florent

**Comment by pyramation** [comment]
I'm open to making something new! I suppose we can grow outside of the spec. Currently most "statements" are things that can be parsed from actual SQL. I suppose the only issue here is there is no actual node called raw_stmts or raw_transaction. What I would suggest in this case, is we add it to the `ast_helpers` schema to achieve this and call it `ast_helpers.raw_transaction`?
